### ISSUE TITLE
Trains not waiting at Provider with 2.0.7

### ISSUE THREAD

**Issue by DodoCooker** [mamoniot/project-cybersyn#182]
When I update from 2.0.6 to 2.0.7 my trains don't get wait conditions for cargo at the Provider stations and therefore insta-leave them. Is there a bug with the latest changes or is there something I need to change in my settings to get the "Cargo >= xxx" wait conditions again?

**Comment by miaopas** [comment]
I also found this issue, so down grade to 2.0.6 currently
