### ISSUE TITLE
Farthest possible train chosen by mod

### ISSUE THREAD

**Issue by MrDj200** [mamoniot/project-cybersyn#198]
I've noticed that the farthest available train is often being chosen for a job. See following image

![image](https://github.com/user-attachments/assets/37a29476-1c5e-45a8-8efd-f9f40827138f)

- **D1**: Main Depot
- **D2**: Small Depot (different station name but same network)
- **P**: Provider
- **R**: Requester

### Expected Behavior:
I'd expect the closest available and compatible train to be chosen.

### Observed Behavior:
Even though there were several compatible trains available in **D1**, which is much closer, the mod chose the train in **D2** to fulfill the job.

### Further Notes:
It doesn't only happen with these specific requests. It seems to happen on any request

**Comment by shockrift** [comment]
IIRC, dispatch is round robin style and longest idle is chosen for next delivery.

**Comment by MrDj200** [comment]
Based on my observations, that's not the case. When the train goes back to **D2**, it is chosen for the next delivery again, even though there are more than 10 others available in another **D1**

**Comment by MrDj200** [comment]
I seem to have messed up something. So my own fault. Sorry
